[phases.setup]
nixPkgs = ["nodejs", "python3", "pip"]

[phases.install]
cmds = [
  "npm install",
  "cd backend && pip install -r requirements.txt"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start" 